name: Continous Deployment workflow

on: 
  push:
    branches:
      - master

jobs:
  cd:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use SSH key
        run: | 
          mkdir -p ~/.ssh/
          echo "${{secrets.MYSECRET}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.email "felipepepe@gmail.com"
          git config --global user.name "felipepepe"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- -r git@github.com:FelipePepe/modulo_cloud_github_actions.git
